### ISSUE TITLE
Problems with REBOUND updates

### ISSUE THREAD

**Issue by gacarita** [shadden/celmech#12] opened 2023-12-06 18:26 UTC
Hi,

I'm getting issues with celmech examples because REBOUND has updated few functions, for example, calculate_orbit doesn't exist anymore, now they are called as only orbit. So far looks like celmech uses those old functions and this does not work with the most recent REBOUND version.

**Comment by shadden** [comment] 2023-12-06 19:03
Hello Gabriel, 
  Thanks for flagging this-- I was aware that rebound was recently updated to version 4 and this has broken some of the functionality of celmech. Its high on my priority list to fix these issues! As a stopgap in the meantime though, you should be able to fix this by working with an older version of rebound. For example, 
```
pip install rebound==3.28
```
should work. (feel free to let me know if it doesn't)

**Comment by shadden** [comment] 2023-12-06 21:47
I just merged a pull request that should fix (most of) the problems with the upgrade to rebound version 4, so re-installing celmech from the GitHub repo should take care of these issues.

**Comment by gacarita** [comment] 2023-12-07 14:11
Hi @shadden,

Thank you. I'll run some tests and let you know if I have any serious problems.

**Comment by gacarita** [comment] 2024-01-10 09:28
Hi @shadden,

I just got time to work again with celmech. So far no bugs on installation.

However, looks like some of functions of celmech are broken.

Starting from quickstartexample.ipynb, this is case is showing different results from the ones in the repo, see the image below.

If you run the example the equations looks similar, but the results not.

![image](https://github.com/shadden/celmech/assets/53542579/c1b98324-9428-4a98-bd47-de504bf29e6a)

I tried few other examples and most of them still broken but there are expections like canonical transformations. 

We have a research group in dynamics and we are quite interested in using this tool in our future studies.

I followed you suggestion to fix rebound at ==3.28 and use old celmech, however this also changes reboundx and them everything bugs out from start, when import libraries.

Right now it works with different results from the repo with this configs

Name: rebound
Version: 4.0.3

Name: reboundx
Version: 4.0.0

Name: celmech
Version: 1.2.0

Name: Theano
Version: 1.0.5

Name: sympy
Version: 1.12

**Comment by shadden** [comment] 2024-01-10 16:24
Hi @gacarita-- I installed celmech in a clean python environment and was able to reproduce your bug; I'm currently working to figure out what's going on and I'll get back to you once I've found a solution

**Comment by shadden** [comment] 2024-01-10 18:25
Hi @gacarita, I tracked down the error and I've uploaded a new version of celmech (1.3.2) to PyPI, so you should be able to pip install the new version. I had a colleague test out a pip install of the new version and everything worked as it should. (It turns out that between old and new versions, scipy changed the behaviour of scipy.special.factorial2 when called with the argument -1. What a headache!)  I'll go ahead and close this issue for now but feel free to raise another if you run in to any more problems.

**Closed by shadden** 2024-01-10 18:25 UTC

**Comment by gacarita** [comment] 2024-01-11 08:49
Hi @shadden,

Thank you. 

So far I was able to reproduce the examples, however there still an error that I'm getting with the example in frequency analyses, looks like the rebound has updated the function `automateSimulationArchive` to `Simulationarchive` and removed/changed the interval argument that might be reason for this.

**Comment by shadden** [comment] 2024-01-11 20:05
Hey @gacarita, thanks for catching this! Reound 4 changed the name of some functions and classes associated with simulation archives. I've updated celmech (now v1.3.3 on PyPI) and the frequency analysis Jupyter example so that everything should run smoothly now!

**Comment by gacarita** [comment] 2024-01-12 08:55
Hi @shadden,

Thank you for the update.
